### ISSUE TITLE
Tests fail with error undefined "function generate_token/3"

### ISSUE THREAD

**Issue by guidotripaldi** [riverrun/phoenix-todoapp#3]
I would trying to use openmaize_jwt for authentication in a REST / API application, so I took a look at this demo to understand how to use it. But it seems that the code is not yet stable because I receive errors both when I'm running the tests, and when I'm trying to access some api.

Running the test I got:

```
$ mix test
** (CompileError) test/controllers/authorize_test.exs:12: undefined function generate_token/3
    (elixir) expanding macro: Kernel.|>/2
    test/controllers/authorize_test.exs:12: TodoApp.AuthorizeTest (module)
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:56: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5

21:46:53.232 [error] GenServer #PID<0.167.0> terminating
** (CompileError) test/controllers/authorize_test.exs:12: undefined function generate_token/3
    (elixir) expanding macro: Kernel.|>/2
    test/controllers/authorize_test.exs:12: TodoApp.AuthorizeTest (module)
    (elixir) src/elixir.erl:223: :elixir.erl_eval/3
    (elixir) src/elixir.erl:211: :elixir.eval_forms/4
    (elixir) src/elixir_compiler.erl:66: :elixir_compiler.eval_compilation/3
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
    (elixir) src/elixir_compiler.erl:30: :elixir_compiler.quoted/3
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:56: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
[phoenix-todoapp-master]$
```

taking a look at the code I see that in every test the function `generate_token` is called with three parameters in every its occurrence, as in the following example

`|> generate_token({0, 1440}, @secret)`

but it is actually an arity/2 function:

`def generate_token(user, {nbf_delay, token_validity})`

I haven't investigated further on this because I'm not sure to understand yet correctly all the code.

Besides this, I'm not sure why I'm getting the following error when I'm trying to login to the server through an api call. After launching the server I issued a POST `curl` call with the following parameters:

`curl -H "Content-Type: application/json" -X POST -d '{"username": "Gladys", "password": "mangoes&gooseberries"}' http://localhost:4000/api/login`

but the server raised this exception:

```
$ mix phoenix.server
[info] Running TodoApp.Endpoint with Cowboy using http://localhost:4000
[info] POST /api/login
[debug] Processing by TodoApp.UserController.login/2
  Parameters: %{"password" => "[FILTERED]", "username" => "Gladys"}
  Pipelines: [:api]
[info] Sent 500 in 78ms
[error] #PID<0.341.0> running TodoApp.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api/login
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Openmaize.Login.call/2
        (openmaize) lib/openmaize/login.ex:78: Openmaize.Login.call(%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{current_user: nil}, before_send: [#Function<1.122760225/1 in Plug.Logger.call/2>], body_params: %{"password" => "mangoes&gooseberries", "username" => "Gladys"}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "localhost", method: "POST", owner: #PID<0.341.0>, params: %{"password" => "mangoes&gooseberries", "username" => "Gladys"}, path_info: ["api", "login"], peer: {{127, 0, 0, 1}, 60320}, port: 4000, private: %{TodoApp.Router => {[], %{}}, :phoenix_action => :login, :phoenix_controller => TodoApp.UserController, :phoenix_endpoint => TodoApp.Endpoint, :phoenix_format => "json", :phoenix_layout => {TodoApp.LayoutView, :app}, :phoenix_pipelines => [:api], :phoenix_route => #Function<8.47793337/1 in TodoApp.Router.match_route/4>, :phoenix_router => TodoApp.Router, :phoenix_view => TodoApp.UserView, :plug_session_fetch => #Function<1.82590416/1 in Plug.Session.fetch_session/1>}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "localhost:4000"}, {"user-agent", "curl/7.49.1"}, {"accept", "*/*"}, {"content-type", "application/json"}, {"content-length", "58"}], request_path: "/api/login", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "1um6dda24836pq0r5sb23ccd2m5h61lq"}], scheme: :http, script_name: [], secret_key_base: "2AvAHXzlkOHae+duzQkuM4LUwcf1MW09PNxoJqdb/P8I84N1CimJwCnOpydT4Gh/", state: :unset, status: nil}, {TodoApp.OpenmaizeEcto, :username})
        (todo_app) web/controllers/user_controller.ex:1: TodoApp.UserController.phoenix_controller_pipeline/2
        (todo_app) lib/todo_app/endpoint.ex:1: TodoApp.Endpoint.instrument/4
        (todo_app) lib/phoenix/router.ex:261: TodoApp.Router.dispatch/2
        (todo_app) web/router.ex:1: TodoApp.Router.do_call/2
        (todo_app) lib/todo_app/endpoint.ex:1: TodoApp.Endpoint.phoenix_pipeline/1
        (todo_app) lib/plug/debugger.ex:93: TodoApp.Endpoint."call (overridable 3)"/2
        (todo_app) lib/todo_app/endpoint.ex:1: TodoApp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Can you give me some hints to overcome these problems and how to correctly use `openmaize_jwt` in an application? It seems that it is not well documented yet (but I can try to write an extended readme file after your hints)

Thanks in advance!

**Comment by riverrun** [comment]
This example app definitely needs a little more love :)
I should have time at the weekend to work on it. I'll get back to you then.

**Comment by guidotripaldi** [comment]
thank you David, let me know if I can help someway to enhance code or documentation.

**Comment by riverrun** [comment]
So the tests pass now, but I've also opened [this issue](https://github.com/riverrun/openmaize_jwt/issues/1) about possibly using Phoenix.Token instead of openmaize_jwt, and the work related to using Phoenix.Token is on the `ditch_jwt` branch.

It would be good to get your feedback on this. Is there any reason why you would want to use JWTs, or would the phoenix api token be good for your purpose?
